#!/bin/sh

# Set these paths appropriately

BIN=/Users/msgeden/Desktop/Libraries/tree-tagger-MacOSX-3.2-intel/bin
CMD=/Users/msgeden/Desktop/Libraries/tree-tagger-MacOSX-3.2-intel/cmd
LIB=/Users/msgeden/Desktop/Libraries/tree-tagger-MacOSX-3.2-intel/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
