#!/bin/sh

# Set these paths appropriately

BIN=/Users/msgeden/Desktop/Libraries/tree-tagger-MacOSX-3.2-intel/bin
CMD=/Users/msgeden/Desktop/Libraries/tree-tagger-MacOSX-3.2-intel/cmd
LIB=/Users/msgeden/Desktop/Libraries/tree-tagger-MacOSX-3.2-intel/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
